
from __future__ import annotations

import argparse
from dataclasses import dataclass

import numpy as np
import torch

from simulator.config import DistributionType, WorkloadConfig
from simulator.generator import WorkloadGenerator

from feature.state import CacheState

from lstm.config import ModelConfig
from lstm.predictor import Predictor

from RL.config import EnvironmentConfig, NetworkConfig
from RL.environment import CacheEvictionEnvironment
from RL.normalizer import StateNormalizer
from RL.network import QNetwork
from RL.baseline import LFUPolicy


@dataclass
class DecisionRecord:
    index: int
    state: np.ndarray
    lfu_action: int
    net_action: int
    agree: bool


def _load_network(checkpoint_path: str, network_config: NetworkConfig) -> QNetwork:
    network = QNetwork(network_config)
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    network.load_state_dict(checkpoint["online_state_dict"])
    network.eval()
    return network


def _net_action(network: QNetwork, state: np.ndarray) -> int:
    with torch.no_grad():
        state_tensor = torch.from_numpy(state).float().unsqueeze(0)
        q_values = network(state_tensor)
        return int(torch.argmax(q_values, dim=1).item())


def _build_environment(
    environment_config: EnvironmentConfig,
    workload_config: WorkloadConfig,
    model_config: ModelConfig,
    lstm_checkpoint: str,
    normalizer: StateNormalizer,
) -> CacheEvictionEnvironment:
    workload = WorkloadGenerator(workload_config)
    cache_state = CacheState()
    predictor = Predictor.from_checkpoint(
        checkpoint_path=lstm_checkpoint,
        model_config=model_config,
        state=cache_state,
    )
    return CacheEvictionEnvironment(
        config=environment_config,
        workload_generator=workload,
        predictor=predictor,
        cache_state=cache_state,
        normalizer=normalizer,
    )


def run_open_loop(
    environment: CacheEvictionEnvironment,
    network: QNetwork,
) -> list[DecisionRecord]:
    """States are generated entirely by LFU's own actions. This is what
    the training-time chronological validation split measured."""
    lfu = LFUPolicy()
    records: list[DecisionRecord] = []

    state = environment.reset()
    idx = 0
    while not environment.done:
        lfu_action = lfu.select_action(state)
        net_action = _net_action(network, state)
        records.append(
            DecisionRecord(
                index=idx,
                state=state.copy(),
                lfu_action=lfu_action,
                net_action=net_action,
                agree=(lfu_action == net_action),
            )
        )
        idx += 1
        result = environment.step(lfu_action)  # LFU drives the trajectory
        state = result.next_state

    return records


def run_closed_loop(
    environment: CacheEvictionEnvironment,
    network: QNetwork,
) -> list[DecisionRecord]:
    """States are generated by the imitation network's own actions
    (exactly what happens during the real benchmark). LFU's action is
    computed at each step for comparison ONLY -- it never drives the
    rollout, so this does not change environment dynamics at all."""
    lfu = LFUPolicy()
    records: list[DecisionRecord] = []

    state = environment.reset()
    idx = 0
    while not environment.done:
        lfu_action = lfu.select_action(state)
        net_action = _net_action(network, state)
        records.append(
            DecisionRecord(
                index=idx,
                state=state.copy(),
                lfu_action=lfu_action,
                net_action=net_action,
                agree=(lfu_action == net_action),
            )
        )
        idx += 1
        result = environment.step(net_action)  # network drives the trajectory
        state = result.next_state

    return records


def summarize(name: str, records: list[DecisionRecord]) -> None:
    n = len(records)
    agreements = sum(r.agree for r in records)
    agreement_rate = agreements / n if n > 0 else 0.0
    first_mismatch = next((r.index for r in records if not r.agree), None)

    print(f"=== {name} ===")
    print(f"decisions: {n:,}")
    print(f"agreement rate: {agreement_rate:.4%}  ({agreements:,}/{n:,})")
    if first_mismatch is None:
        print("no mismatches found")
    else:
        print(f"first mismatch at decision index: {first_mismatch:,}")
        r = records[first_mismatch]
        print(f"  state at first mismatch:\n{r.state}")
        print(f"  lfu_action={r.lfu_action}  net_action={r.net_action}")
    print()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", default="checkpoints_lfu_imitation/imitation.pt")
    parser.add_argument("--lstm-checkpoint", default="lstm_popularity_predictor.pt")
    parser.add_argument("--seed", type=int, default=43)
    parser.add_argument("--num-requests", type=int, default=5_000)
    parser.add_argument("--num-keys", type=int, default=5_000)
    args = parser.parse_args()

    environment_config = EnvironmentConfig()
    network_config = NetworkConfig()
    model_config = ModelConfig(event_features=8, candidate_features=3)
    normalizer = StateNormalizer()

    workload_config = WorkloadConfig(
        num_keys=args.num_keys,
        num_requests=args.num_requests,
        distribution=DistributionType.ZIPFIAN,
        seed=args.seed,
    )

    network = _load_network(args.checkpoint, network_config)

    # Two FRESH environments (fresh CacheState + fresh Predictor instance
    # each) built from the identical workload_config -- WorkloadGenerator
    # is deterministic given (seed, config), so both environments see the
    # exact same request stream, but the imitation network is allowed to
    # take different actions than LFU in the closed-loop run, producing a
    # genuinely different resident-key trajectory from that point on.
    open_loop_env = _build_environment(
        environment_config, workload_config, model_config, args.lstm_checkpoint, normalizer
    )
    closed_loop_env = _build_environment(
        environment_config, workload_config, model_config, args.lstm_checkpoint, normalizer
    )

    print(f"[Diagnostic] seed={args.seed} num_requests={args.num_requests} num_keys={args.num_keys}\n")

    open_loop_records = run_open_loop(open_loop_env, network)
    summarize("TEST 1: OPEN LOOP (states generated by LFU)", open_loop_records)

    closed_loop_records = run_closed_loop(closed_loop_env, network)
    summarize("TEST 2: CLOSED LOOP (states generated by imitation network)", closed_loop_records)

    open_rate = sum(r.agree for r in open_loop_records) / max(len(open_loop_records), 1)
    closed_rate = sum(r.agree for r in closed_loop_records) / max(len(closed_loop_records), 1)
    print("=== Verdict ===")
    print(f"open-loop agreement:   {open_rate:.4%}")
    print(f"closed-loop agreement: {closed_rate:.4%}")
    if open_rate - closed_rate > 0.02:
        print(
            "Gap confirms covariate shift: the network agrees with LFU far more "
            "often on LFU-generated states than on states produced by its own "
            "prior actions. This is compounding-error behavioral cloning "
            "divergence, not a slot-indexing/masking/checkpoint bug."
        )
    else:
        print(
            "No meaningful open-loop/closed-loop gap found. If this happens, "
            "the covariate-shift hypothesis is NOT supported and the ~10pp "
            "benchmark gap needs a different explanation -- re-examine "
            "sections 1-5 and 7-12 of the investigation instead."
        )


if __name__ == "__main__":
    main()